# Generated by Django 4.2.6 on 2023-10-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panelUser', '0002_profilemanager_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemanager',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/'),
        ),
    ]
