# Generated by Django 4.2.6 on 2023-10-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
